LibraryMVC/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;

namespace LibraryMVC.Models
{
    public class Login
    {

        // database connection with user name or password to validate the user name or password 
        public String SName { get; set; }
        public String SPassword { get; set; }


        //global declaration of the variable 
        SqlConnection connection;
        String connection_String = "Data Source=LAPTOP-TUCRR34F\\SQLEXPRESS;Initial Catalog=Library;Integrated Security=True";
        SqlCommand command;
        SqlDataReader Datareader;

        // implemtneting the method of the interface
        //using the concept of oops define a single method that is used to insert delete and update the record in the table 
        public void InsDelUpdt(String qry)
        {

            connection = new SqlConnection(connection_String);
            connection.Open();
            command = new SqlCommand(qry, connection);
            command.ExecuteNonQuery();
            connection.Close();
        }

        // user define method that is used to get the record from the table
        public DataTable Srch(String qry)
        {
            DataTable tbl = new DataTable();


            connection = new SqlConnection(connection_String);

            connection.Open();
            command = new SqlCommand(qry, connection);

            Datareader = command.ExecuteReader();

            tbl.Load(Datareader);

            connection.Close();

            return tbl;
        }



    }
}

LibraryMVC/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.Models;
namespace LibraryMVC.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        private MemberBookEntity dbtest = new MemberBookEntity();
        public ActionResult ViewBook()
        {
            return View(dbtest.BOoks.ToList());
        }

        // GET: Book/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] BOok BookID)
        {

            if (!ModelState.IsValid)
                return View();
            dbtest.BOoks.Add(BookID);
            dbtest.SaveChanges();
            //Response.Redirect("StudentAdmission",true);
            return RedirectToAction("ViewBook");

        }

        // GET: Book/Edit/5
        public ActionResult Edit(int id)
        {
            var BookToEdit = (from m in dbtest.BOoks where m.id== id select m).First();

            return View(BookToEdit);
        }

        // POST: Book/Edit/5
        [HttpPost]
        public ActionResult Edit(BOok BookToEdit)
        {
            var orignalRecord = (from m in dbtest.BOoks where m.id == BookToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            dbtest.Entry(orignalRecord).CurrentValues.SetValues(BookToEdit);

            dbtest.SaveChanges();
            return RedirectToAction("ViewBook");



        }

        // GET: Book/Delete/5
        public ActionResult Delete(BOok BookID)
        {
            var d = dbtest.BOoks.Where(x => x.id == BookID.id).FirstOrDefault();
            dbtest.BOoks.Remove(d);
            dbtest.SaveChanges();
            return RedirectToAction("ViewBook");
        }

        // POST: Book/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryMVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.Models;
namespace LibraryMVC.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        //this method is used to validte the user name or password of the user after verfiying the both the control will  transfer to another page 
        public ActionResult validate(Login log)
        {

            Login objConnection = new Login();
            String query = "select * from Admin where SName='" + log.SName + "' and SPassword='" + log.SPassword + "'";
            DataTable tbl = new DataTable();
            tbl = objConnection.Srch(query);

            if (tbl.Rows.Count > 0)
            {

                return View("AdminZone");
            }
            else
            {
                return View("WrongPassword");
            }

        }
    }
}

LibraryMVC/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.Models;
namespace LibraryMVC.Controllers
{
    public class MemberController : Controller
    {
        // GET: Member
       private MemberBookEntity db = new MemberBookEntity();
        public ActionResult ViewMember()
        {
            return View(db.Members.ToList());
        }

        // GET: Member/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Member/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Member/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Member studentToCreate)
        {
            if (!ModelState.IsValid)
                return View();
            db.Members.Add(studentToCreate);
            db.SaveChanges();
            //Response.Redirect("StudentAdmission",true);
            return RedirectToAction("ViewMember");


        }

        // GET: Member/Edit/5
        public ActionResult Edit(int id)
        {
            var studentToEdit = (from m in db.Members where m.id== id select m).First();
            return View(studentToEdit);
        }

        // POST: Member/Edit/5
        [HttpPost]
        public ActionResult Edit(Member studentToEdit)
        {
            var orignalRecord = (from m in db.Members where m.id == studentToEdit.id select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            db.Entry(orignalRecord).CurrentValues.SetValues(studentToEdit);

            db.SaveChanges();
            return RedirectToAction("ViewMember");

        }

        // GET: Member/Delete/5
        public ActionResult Delete(Member studentToDelete)
        {
            var d = db.Members.Where(x => x.id == studentToDelete.id).FirstOrDefault();
            db.Members.Remove(d);
            db.SaveChanges();

            return View("ViewMember");
        }

        // POST: Member/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryMVC/Views/Login/AdminZone.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Admin Zone </h2>

<a href='@Url.Action("ViewBook","Book")' class="btn btn-danger">Add Book</a>
<a href='@Url.Action("ViewMember","Member")' class="btn btn-danger">Add Member</a>
<br/>

<a href='@Url.Action("Login","Login")' class="btn btn-danger">Back to Login Page</a>

LibraryMVC/Views/Login/Login.cshtml
@{
    ViewBag.Title = "Login";
}


<style>
    tr, td {
        border: 0px solid red;
        height: 30px;
        width: 500px;
        font-size: 30px;
        color: black;
        padding: 10px;
    }
</style>


<section class="ab-info-main py-md-5 py-4">
    <div class="container py-md-6 py-6">
        <h3 class="tittle text-center mb-lg-5 mb-3"><span class="sub-tittle"></span>Admin Login </h3>
        <div class="row contact-main-info">
            <div class="col-md-12 contact-right">
                <form action="Validate" method="post">
                    <table>
                        <tr>
                            <td>Enter User Name</td>
                            <td>
                                <input id="AdminUserName" name="SName" type="text" class="email" placeholder="Email" required="" />
                            </td>
                        </tr>
                        <tr>
                            <td>Enter Password</td>
                            <td>
                                <input id="AdminPassword" name="SPassword" class="email" type="text" placeholder="Password" required="" />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <div class="read mt-3">
                                    <input id="submit" name="submit" type="submit" value="SignIn" class="btn btn-primary" />
                                </div>
                            </td>

                        </tr>
                    </table>
            </div>
            </form>
        </div>

    </div>


    </div>
</section>

LibraryMVC/Views/Login/WrongPassword.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Sorry Wrong User Name or Password</h2>



<a href='@Url.Action("Login","Login")' class="btn btn-danger">Back to Login Page</a>